#  (APP NAME)
version: "3"

services:
  <servicename>:
    container_name: $CONTAINER_NAME
    image: <TBD>
    restart: unless-stopped # "no" always on-failure unless-stopped
    # ports:
    # - $PORT:<TBD>
    # networks: 
    #   - default
    #   - proxy
    volumes:
      - $CONFIG_PATH/:<TBD>

networks:
  default:
  proxy:
    name: $NETWORK
    external: true
