#  (APP NAME)
version: "3"

services:
  flame:
    container_name: $CONTAINER_NAME
    image: <TBD>
    restart: unless-stopped # "no" always on-failure unless-stopped
    ports:
    - 127.0.0.1:$PORT:<TBD>
    volumes:
      - $CONFIG_PATH/:<TBD>
    security_opt:
      - no-new-privileges:true
