services:

  caddy:
    # image: caddy:2
    build: .
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN
      - EMAIL_FOR_ACME
      - CF_API_TOKEN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${APPDATA}/data:/data
      - ${APPDATA}/config:/config

networks:
  default:
    name: $NETWORK
    external: true
