services:

  caddy:
    # image: caddy:2
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN1
      - DOMAIN2
      - EMAIL_FOR_ACME
      - CF_API_TOKEN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${APPDATA}/data:/data
      - ${APPDATA}/config:/config
#     network_mode: "host"

networks:
  default:
    name: $NETWORK
    external: true
