#  FLAME DASHBOARD
version: "3"

services:
  flame:
    container_name: $CONTAINER_NAME
    image: pawelmalak/flame
    restart: unless-stopped # "no" always on-failure unless-stopped
    ports:
    - 127.0.0.1:$PORT:5005
    volumes:
      - $CONFIG_PATH/:/app/data
    environment:
      - PASSWORD=$FLAME_PASSWORD
    security_opt:
      - no-new-privileges:true
