#  FLAME DASHBOARD
version: "3"

services:
  flame:
    container_name: $CONTAINER_NAME
    image: pawelmalak/flame
    restart: unless-stopped # "no" always on-failure unless-stopped
    # ports:
    # - 5005:5005
    volumes:
      - $APPDATA/:/app/data
    environment:
      - PASSWORD=$FLAME_PASSWORD

networks:
  default:
    name: $NETWORK
    external: true
