# NEXTCLOUD
version: '3'

services:
  db:
    container_name: ${CONTAINER_NAME}-db
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - $APPDATA/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - .env

  redis:
    container_name: ${CONTAINER_NAME}-redis
    image: redis:alpine
    restart: always

  app:
    container_name: $CONTAINER_NAME-app
    # image: nextcloud:apache
    build: .
    restart: always
    # ports:
      # - 127.0.0.1:8080:80
    networks:
      - default
      - proxy
    volumes:
      - $APPDATA/ncdata:/var/www/html
      - $USERDATA:/var/www/html/data
      - $SHARED:/mnt/
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_FQDN
      - TRUSTED_PROXIES=caddy
      - OVERWRITEPROTOCOL=https
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db-backup:
    container_name: $CONTAINER_NAME-db-backup
    image: tiredofit/db-backup
    restart: always
    networks:
      - default
    volumes:
      - $APPDATA/db_backups/backups:/backup
      - $APPDATA/db_backups/logfiles:/assets/logfiles
      - ./db_backup/scripts_pre:/assets/scripts/pre
      - ./db_backup/scripts_post:/assets/scripts/post
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=$CONTAINER_NAME-db
      - DB_NAME=$MYSQL_DATABASE
      - DB_USER=$MYSQL_USER
      - DB_PASS=$MYSQL_PASSWORD
      - CHECKSUM=SHA1
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DB_DUMP_FREQ
      - DB_DUMP_BEGIN
      - DB_CLEANUP_TIME
    env_file:
      - .env
    depends_on:
      - db

networks:
  default:
  proxy:
    name: $NETWORK
    external: true
