#  PORTAINER
version: "3"

services:
  portainer:
    container_name: $CONTAINER_NAME
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped # "no" always on-failure unless-stopped
    # ports:
    # - $PORT:9443
    networks:
      - default
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_PATH/:/data

networks:
  default:
  proxy:
    name: $NETWORK
    external: true
